/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedMaxSettingsRouteImport } from './routes/_authenticated/max-settings'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedQuizzesIndexRouteImport } from './routes/_authenticated/quizzes/index'
import { Route as AuthenticatedQuizzesEditRouteImport } from './routes/_authenticated/quizzes/edit'
import { Route as AuthenticatedQuizzesNewRouteImport } from './routes/_authenticated/quizzes/new'
import { Route as AuthenticatedQuizzesPreviewRouteImport } from './routes/_authenticated/quizzes/preview'
import { Route as ApiPublicMaxWebhookRouteImport } from './routes/api/public/max-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaxSettingsRoute =
  AuthenticatedMaxSettingsRouteImport.update({
    id: '/max-settings',
    path: '/max-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesIndexRoute =
  AuthenticatedQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizzesEditRoute =
  AuthenticatedQuizzesEditRouteImport.update({
    id: '/quizzes/edit',
    path: '/quizzes/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuizzesNewRoute = AuthenticatedQuizzesNewRouteImport.update({
  id: '/quizzes/new',
  path: '/quizzes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuizzesPreviewRoute =
  AuthenticatedQuizzesPreviewRouteImport.update({
    id: '/quizzes/preview',
    path: '/quizzes/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMaxWebhookRoute = ApiPublicMaxWebhookRouteImport.update({
  id: '/api/public/max-webhook',
  path: '/api/public/max-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/max-settings': typeof AuthenticatedMaxSettingsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/quizzes/edit': typeof AuthenticatedQuizzesEditRoute
  '/quizzes/new': typeof AuthenticatedQuizzesNewRoute
  '/quizzes/preview': typeof AuthenticatedQuizzesPreviewRoute
  '/api/public/max-webhook': typeof ApiPublicMaxWebhookRoute
  '/quizzes/': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/events': typeof AuthenticatedEventsRoute
  '/max-settings': typeof AuthenticatedMaxSettingsRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/quizzes/edit': typeof AuthenticatedQuizzesEditRoute
  '/quizzes/new': typeof AuthenticatedQuizzesNewRoute
  '/quizzes/preview': typeof AuthenticatedQuizzesPreviewRoute
  '/api/public/max-webhook': typeof ApiPublicMaxWebhookRoute
  '/quizzes': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/max-settings': typeof AuthenticatedMaxSettingsRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/quizzes/edit': typeof AuthenticatedQuizzesEditRoute
  '/_authenticated/quizzes/new': typeof AuthenticatedQuizzesNewRoute
  '/_authenticated/quizzes/preview': typeof AuthenticatedQuizzesPreviewRoute
  '/api/public/max-webhook': typeof ApiPublicMaxWebhookRoute
  '/_authenticated/quizzes/': typeof AuthenticatedQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/dashboard'
    | '/events'
    | '/max-settings'
    | '/referrals'
    | '/results'
    | '/users'
    | '/quizzes/edit'
    | '/quizzes/new'
    | '/quizzes/preview'
    | '/api/public/max-webhook'
    | '/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/dashboard'
    | '/events'
    | '/max-settings'
    | '/referrals'
    | '/results'
    | '/users'
    | '/quizzes/edit'
    | '/quizzes/new'
    | '/quizzes/preview'
    | '/api/public/max-webhook'
    | '/quizzes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/events'
    | '/_authenticated/max-settings'
    | '/_authenticated/referrals'
    | '/_authenticated/results'
    | '/_authenticated/users'
    | '/_authenticated/quizzes/edit'
    | '/_authenticated/quizzes/new'
    | '/_authenticated/quizzes/preview'
    | '/api/public/max-webhook'
    | '/_authenticated/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ApiPublicMaxWebhookRoute: typeof ApiPublicMaxWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/max-settings': {
      id: '/_authenticated/max-settings'
      path: '/max-settings'
      fullPath: '/max-settings'
      preLoaderRoute: typeof AuthenticatedMaxSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/': {
      id: '/_authenticated/quizzes/'
      path: '/quizzes'
      fullPath: '/quizzes/'
      preLoaderRoute: typeof AuthenticatedQuizzesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/edit': {
      id: '/_authenticated/quizzes/edit'
      path: '/quizzes/edit'
      fullPath: '/quizzes/edit'
      preLoaderRoute: typeof AuthenticatedQuizzesEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/new': {
      id: '/_authenticated/quizzes/new'
      path: '/quizzes/new'
      fullPath: '/quizzes/new'
      preLoaderRoute: typeof AuthenticatedQuizzesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quizzes/preview': {
      id: '/_authenticated/quizzes/preview'
      path: '/quizzes/preview'
      fullPath: '/quizzes/preview'
      preLoaderRoute: typeof AuthenticatedQuizzesPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/max-webhook': {
      id: '/api/public/max-webhook'
      path: '/api/public/max-webhook'
      fullPath: '/api/public/max-webhook'
      preLoaderRoute: typeof ApiPublicMaxWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedMaxSettingsRoute: typeof AuthenticatedMaxSettingsRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedQuizzesEditRoute: typeof AuthenticatedQuizzesEditRoute
  AuthenticatedQuizzesNewRoute: typeof AuthenticatedQuizzesNewRoute
  AuthenticatedQuizzesPreviewRoute: typeof AuthenticatedQuizzesPreviewRoute
  AuthenticatedQuizzesIndexRoute: typeof AuthenticatedQuizzesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedMaxSettingsRoute: AuthenticatedMaxSettingsRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedQuizzesEditRoute: AuthenticatedQuizzesEditRoute,
  AuthenticatedQuizzesNewRoute: AuthenticatedQuizzesNewRoute,
  AuthenticatedQuizzesPreviewRoute: AuthenticatedQuizzesPreviewRoute,
  AuthenticatedQuizzesIndexRoute: AuthenticatedQuizzesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ApiPublicMaxWebhookRoute: ApiPublicMaxWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
